easy_admin:
  entities:
    # change the following to the namespaces of your own entities
    - App\Entity\Gender
    - App\Entity\Activity
    - App\Entity\User
    - App\Entity\Type
    - App\Entity\Close
